### ISSUE TITLE
accessing geeTools

### ISSUE THREAD

**Issue by XMV069** [aazuspan/geeScripts#4]
Hi, 
how can i access the geeTools directly to my GEE reader scripts tab?
I am interested in the DOS script
Sometimes there is  GEE direct link?

Thanks,

Xavier

**Comment by aazuspan** [comment]
Sure thing, here's the sharing link for the repo which should allow you to access it in the Code Editor: https://code.earthengine.google.com/?accept_repo=users/aazuspan/geeTools
